sudo: required

dist: trusty

language: node_js

node_js:
  - 10
  - 12

cache:
  yarn: true
  directories:
    - 'node_modules'

install: yarn --frozen-lockfile

jobs:
  include:
    # Run tests in parallel
    - stage: test
      script: yarn test:lint-js
    - script: yarn test:unit --runInBand
      # Upload coverage reports to Codecov
      after_success: yarn coverage:upload -t ${CODECOV_TOKEN}
    - stage: publish
      script: skip
      # Publish package to NPM
      deploy:
        provider: script
        skip_cleanup: true
        on:
          all_branches: true
        script: yarn release
